spring:
    devtools:
        livereload:
            port: 34730
    datasource:
        url: jdbc:mysql://192.168.1.108:3306/library?useUnicdeo=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: root
server:
    port: 8081
mybatis:
    mapper-locations: classpath:/mapper/*.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    type-handlers-package: cn.wsg.library.dao.typehandler